configurl: http://localhost:8079

spring:
  application:
    name: "gateway-server"
  cloud:
    config:
      profile: local
      uri: ${configurl}
  config:
    import: configserver:${configurl}


