configurl: http://localhost:8079

spring:
  application:
    name: "gateway-server"
  cloud:
    config:
      profile: local
      uri: ${configurl}
      enabled: true
    service-registry:
      auto-registration:
        enabled: true
    discovery:
      enabled: true
  config:
    import: configserver:${configurl}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
