spring:
  application:
    name: "notification-service"
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: notificationCreatedFunction
      bindings:
        notificationCreatedFunction-out-0:
          destination: notification-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8110

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true


