spring:
  application:
    name: "identity-service"
  datasource:
    url: jdbc:postgresql://localhost:5434/identity
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: identityCreatedFunction
      bindings:
        identityCreatedFunction-out-0:
          destination: identity-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
