apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: comturkcellcrm-microservices-hw4-identity-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: identity-service-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
