apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-cart
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-cart
  template:
    metadata:
      labels:
        app: mongo-cart
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-cart-secret
          volumeMounts:
            - name: mongo-cart-storage
              mountPath: /data/db
      volumes:
        - name: mongo-cart-storage
          persistentVolumeClaim:
            claimName: mongo-cart-pvc
