apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: microservices
spec:
  selector:
    app: customer-service
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
