apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-identity
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-identity
  template:
    metadata:
      labels:
        app: postgres-identity
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-identity-config
            - secretRef:
                name: postgres-identity-secret
          volumeMounts:
            - name: postgres-identity-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-identity-storage
          persistentVolumeClaim:
            claimName: postgres-identity-pvc
