apiVersion: v1
kind: Service
metadata:
  name: postgres-identity
  namespace: microservices
spec:
  selector:
    app: postgres-identity
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
