spring:
  application:
    name: "customer-service"
  datasource:
    url: jdbc:mysql://localhost:3307/customer?useSSL=false&serverTimezone=UTC
    username: mysql
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: customerCreatedFunction
      bindings:
        customerCreatedFunction-out-0:
          destination: customer-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
