apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-order-pv
  namespace: microservices
  labels:
    type: local
    app: postgres-order
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-order"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: postgres-order
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-identity-pv
  namespace: microservices
  labels:
    type: local
    app: postgres-identity
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-identity"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-identity-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: postgres-identity
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-product-pv
  namespace: microservices
  labels:
    type: local
    app: mongo-product
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo-product"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-product-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: mongo-product
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-cart-pv
  namespace: microservices
  labels:
    type: local
    app: mongo-cart
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo-cart"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-cart-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: mongo-cart
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-customer-pv
  namespace: microservices
  labels:
    type: local
    app: mysql-customer
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-customer"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-customer-pvc
  namespace: microservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: mysql-customer
