apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
      annotations:
        configserver-dependency: "true"
    spec:
      initContainers:
        - name: wait-for-config-server
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until wget -T 5 -qO- http://config-server-service:8079/actuator/health; do echo waiting for config-server; sleep 10; done;",
            ]
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_CLOUD_CONFIG_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: SPRING_CLOUD_CONFIG_PROFILE
            - name: CONFIGURL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: CONFIGURL
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
  namespace: microservices
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8888
      targetPort: 8888
