apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        discoveryserver-dependency: "true"
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until wget -T 5 -qO- http://discovery-server-service:8888/actuator/health; do echo waiting for discovery-server; sleep 10; done;",
            ]
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8130
          env:
            - name: SPRING_CLOUD_CONFIG_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: SPRING_CLOUD_CONFIG_PROFILE
            - name: CONFIGURL
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: CONFIGURL
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8130
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8130
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  namespace: microservices
spec:
  selector:
    app: product-service
  ports:
    - port: 8130
      targetPort: 8130
