apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-persistent-volumes.yaml
  - 03-databases.yaml
  - 04-kafka.yaml
  - 05-config-server.yaml
  - 06-discovery-server.yaml
  - 07-gateway-server.yaml
  - 08-customer-service.yaml
  - 09-identity-service.yaml
  - 10-notification-service.yaml
  - 11-order-service.yaml
  - 12-product-service.yaml
  - 13-cart-service.yaml

commonLabels:
  app.kubernetes.io/part-of: microservices-app
  app.kubernetes.io/managed-by: kustomize

images:
  - name: config-server
    newName: comturkcellcrm-microservices-hw4-config-server
    newTag: latest
  - name: discovery-server
    newName: comturkcellcrm-microservices-hw4-discovery-server
    newTag: latest
  - name: gateway-server
    newName: comturkcellcrm-microservices-hw4-gateway-server
    newTag: latest
  - name: customer-service
    newName: comturkcellcrm-microservices-hw4-customer-service
    newTag: latest
  - name: identity-service
    newName: comturkcellcrm-microservices-hw4-identity-service
    newTag: latest
  - name: notification-service
    newName: comturkcellcrm-microservices-hw4-notification-service
    newTag: latest
  - name: order-service
    newName: comturkcellcrm-microservices-hw4-order-service
    newTag: latest
  - name: product-service
    newName: comturkcellcrm-microservices-hw4-product-service
    newTag: latest
  - name: cart-service
    newName: comturkcellcrm-microservices-hw4-cart-service
    newTag: latest
