apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: microservices
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-client
      port: 9092
      targetPort: 9092
    - name: kafka-external
      port: 9094
      targetPort: 9094
  type: ClusterIP
