spring:
  application:
    name: "discovery-server"

server:
  port: 8888

eureka:
  instance:
    hostname: "discovery-server"
  client:
    serviceUrl:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: false
    fetch-registry: false