configurl: http://localhost:8079

spring:
  application:
    name: "discovery-server"
  cloud:
    config:
      profile: local
      uri: ${configurl}
  config:
    import: optional:configserver:${configurl}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
