configurl: http://localhost:8079

spring:
  application:
    name: "product-service"
  cloud:
    config:
      profile: local
      uri: ${configurl}
  config:
    import: optional:configserver:${configurl}
