spring:
  application:
    name: "product-service"
  data:
    mongodb:
      uri: mongodb://mongouser:test@localhost:27018/product?authSource=admin
      database: product

server:
  port: 8130

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true