apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
spec:
  selector:
    app: notification-service
  ports:
    - port: 8110
      targetPort: 8110
  type: ClusterIP
