spring:
  application:
    name: "cart-service"
  data:
    mongodb:
      uri: mongodb://mongouser:test@localhost:27019/cart?authSource=admin
      database: cart
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: cartCreatedFunction
      bindings:
        cartCreatedFunction-out-0:
          destination: cart-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8140

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
