apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-order-config
            - secretRef:
                name: postgres-order-secret
          volumeMounts:
            - name: postgres-order-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-order-storage
          persistentVolumeClaim:
            claimName: postgres-order-pvc
